config/routes.rb
Manderlay::Application.routes.draw do
 
  resources :movies do
    resources :comments, shallow: true
    get "cast/new", to: 'movies#new_cast', as: :new_cast
    post "cast", to: 'movies#create_cast', as: :create_cast
  end
  resources :people

  root 'movies#index'

end

app/models/cast.rb
class Cast < ActiveRecord::Base
  belongs_to :movie
  belongs_to :person
  ROLES = ['actor','director', 'writer', 'producer'].sort
  validates :role, :inclusion => { :in => ROLES, allow_nil: true}
  validates :movie_id, uniqueness: { scope: [:person_id,:role]}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :movie

	validates_presence_of :body
	validates_length_of :body, maximum: 500
	
	validates_presence_of :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :comments, :dependent => :destroy
	has_many :people, through: :casts
	has_many :casts, :dependent => :destroy
	validates :title, uniqueness: { scope: [:duration, :synopsis, :year, :category]}
	validates_presence_of :title

	
	scope :bigger_than_duration, ->(duration) { where('duration > ?', duration)}
	scope :smaller_than_duration, ->(duration) { where('duration < ?', duration)}
	scope :bigger_than_year, ->(year) { where('year > ?', year)}
	scope :smaller_than_year, ->(year) { where('year < ?', year)}
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :movies, through: :casts
	has_many :casts, :dependent => :destroy
	validates :name, uniqueness: { scope: :surname}

	def complete_name
		"#{self.name} #{self.surname}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
def set_locale
	if params[:locale].present?
		locale = param[:locale].downcase.to_sym
		if I18n.available_locales.include? locale
			 locale
		else
			I18n.locale = I18n.default_locale
		end
	end
end

end

app/controllers/casts_controller.rb
class CastsController < ApplicationController

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_movie, except: [:show, :edit, :update, :destroy]

  def index
    @comments = @movie.comments
  end

  def create
    @comment = @movie.comments.create comment_params
    respond_to do |format|
          if @comment.save
            format.html { redirect_to movie_comments_path(@movie)}
            format.json { render action: 'show', status: :created, location: @movie }
          else
            format.html { render action: 'new' }
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
      end
  end

  def show
    @comment = Comment.new
  end

  def new
    @comment = @movie.comments.build
  end

  def edit
    @comment = Comment.find(params[:id])
    @movie = @comment.movie
  end

  def update
    @comment = Comment.find(params[:id])
    @movie = @comment.movie
    respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to movie_comments_path(@movie) }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @movie = @comment.movie
    @comment.destroy
    respond_to do |format|
        format.html { redirect_to movie_comments_path(@movie) }
        format.json { head :no_content }
      end
  end

  private
  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, except: [:create, :new, :index]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @comments =  @movie.comments
    @people =  @movie.people
    @casts = Cast.all
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def new_cast
    @cast = @movie.casts.build
  end

  def create_cast
    @cast = @movie.casts.build(cast_params)
    respond_to do |format|
      if @cast.save
        format.html { redirect_to movies_path }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new_cast' }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_comments_path(@movie), notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:movie_id]||params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :duration, :synopsis, :year, :category)
    end

    def cast_params
      params.require(:cast).permit(:person_id, :role)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_action :set_person, except: [:index, :new, :create]

  def index
    @people = Person.all
  end

  def create
    @person = Person.create person_params
    respond_to do |format|
          if @person.save
            format.html { redirect_to people_path(@person), notice: 'Person was successfully created.' }
            format.json { render action: 'show', status: :created, location: @movie }
          else
            format.html { render action: 'new' }
            format.json { render json: @person.errors, status: :unprocessable_entity }
          end
      end
  end

  def edit
  end

  def new
    @person = Person.new
  end

  def update
      @person = Person.find(params[:id])
      respond_to do |format|
        if @person.update(person_params)
          format.html { redirect_to people_path(@person), notice: 'Person was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
  end

  def show
    @movie = @person.movies
  end

  def destroy
  @person.destroy
  respond_to do |format|
      format.html { redirect_to people_path }
      format.json { head :no_content }
    end
  end

private
  def set_person
    @person = Person.find(params[:id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def person_params
    params.require(:person).permit(:name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/casts/_form_cast.html.erb
<%= form_for(@cast, url: movie_create_cast_path(@movie)) do |f| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person %><br>
    <%= f.select :person, Person.all.map {|p| [p.name, p.id]} %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, 
      Cast::ROLES.map {|r| [r.titleize, r]}  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casts/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Back to Movies', movies_path %> |
<%= link_to 'Back to Comments', comment_path %>

app/views/casts/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment_path(comment) %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
   <td> <%= link_to 'Destroy', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_movie_comment_path %>

app/views/casts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comment_path %>

app/views/comments/_form.html.erb
<%= form_for([@movie,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comments</h1>

<%= render 'form' %>

<%= link_to 'Back to Movies', movies_path %> |
<%= link_to 'Back to Comments', movie_comments_path(@movie) %>

app/views/comments/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment_path(comment) %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td> <%= link_to 'Destroy', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_movie_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manderlay</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis, placeholder: "Write your text here" %>
  </div>
   <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
   <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_form_cast.html.erb
<%= form_for(@cast, url: movie_create_cast_path(@movie)) do |f| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.select :person_id, Person.all.map {|p| [p.name + " " + p.surname, p.id]} %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, 
    Cast::ROLES.map {|r| [r.titleize, r]}  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<body>
  <header class="row">
    <h1>Editing movie</h1>
  </header>
  <section class="row">
    <div class="seven columns">
      <%= render 'form' %>
    </div>
  </section>
  <section class="row">
    <%= link_to 'Show', @movie %> |
    <%= link_to 'Back', movies_path %>
  </section>
</body>

app/views/movies/index.html.erb
<head>
  <title>Movie's Application</title>
</head>

<body>
  <header>
    <div class="bck dark color white padding">
      <h1 class="row text center bold">My movies app</h1>
      <nav>
<!--         <ul>
          <li><a>1</a></li>
          <li><a>1</a></li>
          <li><a>1</a></li>
        </ul> -->
      </nav>
    <div>
  </header>

  <section class="row">
   <% @movies.each do |movie| %>
    <article class="bck light column_4 margin-top padding movies-height relative">
      <ul class="li-none">
        <li><p><strong><%= t('movie.title').capitalize %> : </strong> <%= movie.title %></p></li>
        <li><p><strong><%= t('movie.duration').capitalize %> : </strong><%= movie.duration %></p></li>
        <li><p><strong><%= t('movie.synopsis').capitalize %> : </strong><%= movie.synopsis %></p></li>
        <li><p><strong><%= t('movie.year').capitalize %> : </strong><%= movie.year %></p></li>
        <li><p><strong><%= t('movie.category').capitalize %> : </strong><%= movie.category %></p></li>
      </ul>

          <nav class="column_3 absolute movies-button-possition">
      <span class="button tiny on-left secondary"><%= link_to t('movie.show').capitalize, movie %></span>
      <span class="button tiny on-right secondary"><%= link_to t('movie.destroy').capitalize, movie, method: :delete, data: { confirm: 'Are you sure?' } %></span><br>
    </nav>
    </article>
    <% end %>
  </section>


  <div class="row">
    <%= link_to t('movie.new').capitalize, new_movie_path %>
  </div>

</body>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/new_cast.html.erb
<head>
  <title>New People</title>
</head>
<body>
  <header>
      <div class= "bck dark color white padding">
        <h1 class="text center bold">My movies app</h1>
      </div>
  </header>

  <section class="row margin-top">
    <article class="column_4 offset_4">
      <%= render 'form_cast' %>
      <span><%= link_to 'Back to Movie Show', movies_path %></span>
    </article>
  </section>
</body>

app/views/movies/show.html.erb
<head>
  <title>Movie Show</title>
</head>
<body>
  <header class="bck dark padding color white">
    <h1 class="row text center bold">My movies app</h1>
  </header>
  <section class="row margin-top">
    <article class="column_4 offset_2">
      <p>
        <strong>Title:</strong>
        <%= @movie.title %>
      </p>
      <p>
        <strong>Duration:</strong>
        <%= @movie.duration %>
      </p>
      <p>
        <strong>Synopsis:</strong>
        <%= @movie.synopsis %>
      </p>
      <p>
        <strong>Year:</strong>
        <%= @movie.year %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= @movie.category %>
      </p>
    </article>
    <div class="column_3 img h256 margin-bottom"></div>
  </section>

  <section class="column_9 offset_2">
    <article class="column_4 on-left">
    <header class="bck theme padding column_4"><h5 class="text bold">COMMENTS<h5></header>
    <div class="bck light margin-bottom padding column_4">
      <% @comments.each do |comment| %>
        <p class="text book"><span class="text bold">Author:</span>  <%= comment.author %></p> 
        <p><span class="text bold">Body: </span> <%= comment.body %><p>
        <hr>
      <% end %>
      <div class= "text center">
        <p class="button"><%= link_to 'Add new comment!', new_movie_comment_path(@movie) %></p> 
      </div>
    </div>
    </article>

    <article class="column_4 on-right">
      <header class="bck color white padding"><h5 class="text bold">CAST</h5> </header>
      <div class="bck light padding" >
      <% if @movie.casts.empty? %>
        <strong>No people is here</strong>
      <% else %>  
      <ul class="li-none">
        <% @movie.casts.each do |c| %>
          <li>
            <%= c.person.complete_name %> 
            (
            <%= c.role.titleize %>
            )
          </li>
        <% end %>
      </ul>
      <% end %>
      <div class= "text center padding">
        <p class="button secondary"><%= link_to 'Add new cast!', movie_new_cast_path(@movie) %></p> 
      </div>
      </div>
    </article>
  </section>
  <section class="row text center">
    <%= link_to 'New Person', new_person_path %> | 
    <%= link_to 'Edit', edit_movie_path(@movie) %> | 
    <%= link_to 'Back', movies_path %>
  </section>

</body>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing People</h1>

<%= render 'form' %>

<%= link_to 'Back to People', people_path(@movie) %> 

app/views/people/index.html.erb
<h1>People Index</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.surname %></td>
        <td><%= link_to 'Show', person_path(person) %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %> |
<%= link_to 'Back to Movies', movies_path %> 

app/views/people/new.html.erb
<head>
  <title>New People</title>
</head>
<body>
  <header>
      <div class= "bck dark color white padding">
        <h1 class="text center bold">My movies app</h1>
      </div>
  </header>

  <section class="row margin-top">
    <article class="column_4 offset_4">
      <%= render 'form' %>
      <span><%= link_to 'Back to People Index', people_path %></span>
    </article>
  </section>
</body>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<%= link_to 'Edit Person', edit_person_path(@person) %> |
<%= link_to 'Back to Index of People', people_path(@movie) %>